erlang:
  image: erlang:1.7
  ports:
    - 8081:8080
  links:
    - redis:redis
  volumes:
    - $HOME/erlang:/data/erlang
  extra_hosts:
    - "rdb.baba.com:192.168.2.13"
    - "tlog1.baba.com:192.168.2.13"
    - "tlog2.baba.com:192.168.2.13"
    - "redis.baba.com:192.168.2.14"


redis:
  image: docker.v909.com/reborn/server
  ports:
    - 6379:6379
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - $HOME/redis-db:/var/lib/redis
