tlog:
  image: docker.v909.com/baba3/tlog-server
  ports:
    - 6660:6660/udp
  volumes:
    - $HOME/tlogs:/data/logs
    - $HOME/hdata:/hdata
  environment:
      LOGS_PATH: /data/logs
      DB_HOST: 192.168.2.13
      DB_PORT: 3306
      DB_USER: baba3tlog
      DB_PASSWORD: baba3tlog$erlang
      DB_NAME: db_baba3_logtool_1
  restart: always