gameserver:
  image: baba3/gamesrv
  ports:
    - 8080:8080
  volumes:
    - $HOME/baba3-log:/data/log
  extra_hosts:
    - "rdb.baba.com:192.168.2.13"
    - "tlog1.baba.com:192.168.59.103"
    - "tlog2.baba.com:192.168.59.103"
    - "redis.baba.com:192.168.2.14"

